temporary enable tests from builds/SIRF/build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -248,7 +248,8 @@ script:
 # print for debugging
 - cat builds/SIRF/build/CMakeCache.txt
 - |
-   ctest --output-on-failure; test_fail=$?
+   # ctest --output-on-failure; test_fail=$?
+   cd builds/SIRF/build && ctest --verbose
    # echo "----------- Killing gadgetron server"
    # killall gadgetron
    if [[ $test_fail -ne 0 ]]; then
